// Full employee workflow against an isolated demo app. Never submit to production.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const require=createRequire(import.meta.url);
const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));
const {expect}=require(require.resolve('playwright/test',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));
const root='http://127.0.0.1:8765';
const python=process.env.EMPLOYEE_PREVIEW_PYTHON;
const serverScript=process.env.EMPLOYEE_PREVIEW_SERVER;
assert(python&&serverScript,'Provide the Python executable and isolated demo server script.');
const server=spawn(python,[serverScript],{cwd:process.cwd(),env:{...process.env,PYTHONPATH:process.cwd()},stdio:['ignore','ignore','pipe']});
let logs='';server.stderr.on('data',chunk=>logs=(logs+chunk.toString()).slice(-5000));
const output=resolve('docs/previews');await mkdir(output,{recursive:true});
const errors=[],checks=[];
let browser;
try {
  let ready=false;
  for(let i=0;i<100;i++){
    try{if((await fetch(root+'/health')).ok){ready=true;break;}}catch{}
    await new Promise(resolve=>setTimeout(resolve,150));
  }
  assert(ready,'Preview server did not start: '+logs);
  let launch={headless:true,args:['--no-sandbox']};
  if(process.env.EMPLOYEE_CHROMIUM_EXECUTABLE)launch.executablePath=process.env.EMPLOYEE_CHROMIUM_EXECUTABLE;
  browser=await chromium.launch(launch);
  const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
  await context.route('https://fonts.googleapis.com/**',route=>route.fulfill({status:200,contentType:'text/css',body:''}));
  await context.route('https://fonts.gstatic.com/**',route=>route.abort());
  const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
  page.setDefaultTimeout(12000);
  await page.goto(root+'/staff/app');
  await page.locator('[name="email"]').fill('crew@example.test');
  await page.locator('[name="password"]').fill('LocalFieldPreviewStaffPassword2026');
  await page.getByRole('button',{name:'Sign in',exact:false}).click();
  await page.getByRole('heading',{name:/Let’s get to work/}).waitFor();
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile home overflows.');
  await page.screenshot({path:output+'/Employee-App-Mobile.png',fullPage:true});
  checks.push('Mobile sign-in, home layout and service worker');
  console.log('Mobile home verified');
  await page.getByRole('link',{name:/Add client/}).click();
  await page.locator('[name="name"]').fill('Sample Site Contact');
  await page.locator('[name="company"]').fill('Sample Storefront');
  await page.locator('[name="email"]').fill(`field.browser.${Date.now()}@example.test`);
  await page.locator('[name="phone"]').fill('813-555-0101');
  await page.getByRole('button',{name:'Save client',exact:false}).click();
  await page.getByRole('heading',{name:'Sample Storefront',exact:true}).waitFor();
  await page.getByRole('button',{name:'New site survey',exact:false}).click();
  await page.locator('[name="title"]').fill('Sample storefront survey');
  await page.locator('[name="address"]').fill('123 Sample Street, Tampa, FL');
  await page.locator('[name="site_contact"]').fill('Sample Contact · 813-555-0101');
  const area=page.locator('[data-area]').first();
  await area.locator('[name="label"]').fill('Left window');
  await area.locator('[name="unit"]').selectOption('ft');
  await area.locator('[name="width"]').fill('3');
  await area.locator('[name="height"]').fill('6');
  await area.locator('[name="product_id"]').selectOption('4');
  await page.locator('#survey-files').setInputFiles(process.env.EMPLOYEE_PREVIEW_PHOTO);
  await expect(page.locator('.file-chip')).toContainText('Device only');
  await context.setOffline(true);
  await page.locator('[name="surface_notes"]').fill('Glass clear. Door decals cover the top glass only.');
  await page.getByRole('button',{name:'Save device draft',exact:true}).click();
  await expect(page.locator('#employee-toast')).toContainText('saved on this phone');
  await page.reload();
  await page.getByRole('heading',{name:'Site surveys.',exact:true}).waitFor();
  await page.getByRole('link',{name:/Sample storefront survey/}).click();
  await expect(page.locator('[name="surface_notes"]')).toHaveValue('Glass clear. Door decals cover the top glass only.');
  await expect(page.locator('.file-chip')).toContainText('Device only');
  await context.setOffline(false);
  await expect(page.locator('#connection-status')).toContainText('Connected');
  await page.getByRole('button',{name:'Save to shop',exact:false}).click();
  await expect(page.locator('#draft-status')).toContainText('Saved to the shop');
  await expect(page.locator('.file-chip')).toContainText('Saved to shop');
  await page.screenshot({path:output+'/Employee-App-Survey.png',fullPage:true});
  await page.getByRole('button',{name:'Submit for review',exact:true}).click();
  await page.getByRole('heading',{name:'Sample storefront survey',exact:true}).waitFor();
  const surveyId=Number(new URL(page.url()).hash.split('/')[1]);
  checks.push('CRM creation, offline survey/photo retention, recovery, sync and submission');
  console.log('Offline survey and sync verified');
  await page.getByRole('button',{name:'Create estimate',exact:false}).click();
  await expect(page.locator('[name="width"]')).toHaveValue('36.0000');
  await expect(page.locator('[name="height"]')).toHaveValue('72.0000');
  await page.getByRole('button',{name:'Calculate estimate',exact:true}).click();
  await page.getByRole('button',{name:'Create order estimate',exact:false}).waitFor();
  await page.screenshot({path:output+'/Employee-App-Estimate.png',fullPage:true});
  await page.getByRole('button',{name:'Create order estimate',exact:false}).click();
  await page.getByRole('heading',{name:'Sample storefront survey',exact:true}).waitFor();
  const jobId=Number(new URL(page.url()).hash.split('/')[1]);
  const jobResponse=await page.request.get(root+'/api/staff/jobs/'+jobId),job=await jobResponse.json();
  assert(job.charges_verified);
  assert.equal(job.quote.lines[0].width,'36.0000');
  await page.getByRole('button',{name:'Send estimate',exact:true}).click();
  await page.getByRole('button',{name:'Confirm & send estimate',exact:true}).click();
  await page.getByRole('button',{name:'Send estimate again',exact:true}).waitFor();
  await page.getByRole('button',{name:'Create invoice',exact:true}).click();
  await expect(page.locator('#employee-dialog')).toContainText('Draft invoice created');
  await page.getByRole('button',{name:'Close',exact:true}).click();
  checks.push('Survey dimensions to catalog estimate, tax total, publish and draft invoice');
  console.log('Estimate and draft invoice verified');
  await page.getByRole('link',{name:'Queue',exact:true}).click();
  await page.getByRole('button',{name:'Available',exact:true}).click();
  const task=page.locator('.task').filter({hasText:job.number}).first();
  await task.getByRole('button',{name:'Accept task',exact:false}).click();
  await page.getByRole('button',{name:'My queue',exact:true}).click();
  const mine=page.locator('.task').filter({hasText:job.number}).first();
  await mine.getByRole('button',{name:'Start',exact:false}).click();
  await expect(mine).toContainText('In progress');
  await page.screenshot({path:output+'/Employee-App-Queue.png',fullPage:true});
  await mine.getByRole('button',{name:'Finish',exact:false}).click();
  checks.push('Task acceptance, personal queue, start timer and completion');
  await page.goto(root+'/staff/app#job/'+jobId);
  await page.getByRole('button',{name:'Proofs',exact:true}).click();
  const proof=page.locator('form[data-form="proof"]');
  await proof.locator('[name="file"]').setInputFiles(process.env.EMPLOYEE_PREVIEW_PHOTO);
  await proof.locator('[name="covers_all_items"]').check();
  await proof.getByRole('button',{name:'Upload & send for approval',exact:false}).click();
  await page.getByRole('heading',{name:'Proof history',exact:true}).waitFor();
  await page.getByRole('button',{name:'Send again',exact:true}).waitFor();
  await page.screenshot({path:output+'/Employee-App-Proofs.png',fullPage:true});
  checks.push('Employee proof attachment, portal publication and truthful email status');
  console.log('Queue and proof upload verified');
  const ownerContext=await browser.newContext({viewport:{width:1280,height:950}});
  const owner=await ownerContext.newPage();owner.on('pageerror',error=>errors.push(error.message));
  await owner.goto(root+'/staff/app');
  await owner.locator('[name="email"]').fill('owner@example.test');
  await owner.locator('[name="password"]').fill('LocalFieldPreviewOwnerPassword2026');
  await owner.getByRole('button',{name:'Sign in',exact:false}).click();
  await owner.getByRole('heading',{name:/Let’s get to work/}).waitFor();
  await owner.screenshot({path:output+'/Employee-App-Desktop.png',fullPage:true});
  await owner.goto(root+'/staff/app#survey/'+surveyId);
  await owner.getByRole('button',{name:'Verify measurements',exact:true}).click();
  await owner.getByRole('button',{name:'Confirm verified measurements',exact:true}).click();
  await expect(owner.locator('.heading')).toContainText('verified');
  const session=await (await owner.request.get(root+'/api/session')).json();
  const shared=await (await owner.request.post(root+'/api/staff/jobs/'+jobId+'/share',{headers:{'X-CSRF-Token':session.csrf},data:{}})).json();
  const customerContext=await browser.newContext();const customer=await customerContext.newPage();
  await customer.goto(root+'/portal');
  const customerSession=await (await customer.request.get(root+'/api/session')).json();
  const exchange=await (await customer.request.post(root+'/api/portal/exchange',{headers:{'X-CSRF-Token':customerSession.csrf},data:{token:new URLSearchParams(new URL(shared.portal_url).hash.slice(1)).get('token')}})).json();
  const customerJob=await (await customer.request.get(root+'/api/portal/job')).json();
  assert(customerJob.job_terms.sections.length>0,'Proof terms must remain available.');
  const accepted=await customer.request.post(root+'/api/portal/accept-quote',{headers:{'X-CSRF-Token':exchange.csrf},data:{name:'Sample Site Contact',confirm:true,version:customerJob.quote_version}});
  assert.equal(accepted.status(),200,await accepted.text());
  await page.goto(root+'/staff/app#job/'+jobId);
  await page.getByRole('button',{name:'Overview',exact:true}).click();
  await page.getByRole('button',{name:'Create invoice',exact:true}).click();
  await expect(page.locator('#employee-dialog')).toContainText('Invoice created for the accepted project scope.');
  const invoiceHref=await page.locator('#employee-dialog a').getAttribute('href');
  const invoice=await page.request.get(root+invoiceHref);
  assert.equal(invoice.status(),200);
  assert((await invoice.text()).includes('Issued invoice'));
  checks.push('Owner survey verification, unchanged customer terms, scope acceptance and issued invoice');
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.goto(root+'/staff/app#estimate/new');
  await page.getByRole('heading',{name:'Build an estimate.',exact:true}).waitFor();
  const catalog=await (await page.request.get(root+'/api/catalog')).json();
  const clients=await (await page.request.get(root+'/api/staff/clients')).json();
  await page.locator('[name="contact_id"]').selectOption(String(clients.contacts.find(c=>c.company==='Sample Storefront').id));
  await page.locator('[name="title"]').fill('Catalog option check');
  const wrapped=catalog.products.find(p=>p.config.is_wrap && p.config.quantity_only);
  await page.locator('[data-product-select]').selectOption(String(wrapped.id));
  await page.getByRole('button',{name:'Calculate estimate',exact:true}).click();
  await page.getByRole('button',{name:'Create order estimate',exact:false}).waitFor();
  assert.equal(await page.locator('[name="width"]').count(),0,'Wrap pricing must use configured product dimensions.');
  const apparel=catalog.products.find(p=>p.config.finished_apparel);
  await page.locator('[data-product-select]').selectOption(String(apparel.id));
  await expect(page.locator('[name="shirt_color"]')).toBeVisible();
  await page.locator('[data-size]').first().fill('2');
  await page.getByRole('button',{name:'Calculate estimate',exact:true}).click();
  await page.getByRole('button',{name:'Create order estimate',exact:false}).waitFor();
  await expect(page.locator('#estimate-price')).toContainText('Garment sizes / placements in scope');
  checks.push('Configured wrap pricing dimensions and apparel size/color/placement pricing');
  for(const width of [360,430,768]){
    await page.setViewportSize({width,height:900});
    await page.goto(root+'/staff/app#home');
    await page.getByRole('heading',{name:/Let’s get to work/}).waitFor();
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Home overflow at '+width);
  }
  assert.deepEqual(errors,[],'Browser console errors: '+errors.join('; '));
  await writeFile(output+'/employee-browser-checks.json',JSON.stringify({checks,errors,viewports:[360,390,430,768,1280],productionWrites:false},null,2));
  console.log(JSON.stringify({checks:checks.length,errors,viewports:[360,390,430,768,1280]}));
} finally {
  if(browser)await browser.close();server.kill('SIGTERM');
}
